### ISSUE TITLE
git issue

### ISSUE THREAD

**Issue by geekjam** [roxma/ncm-phpactor#6]
PS D:\WinTools\Office\Neovim\share\nvim\plugged\phpactor> composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 26 installs, 0 updates, 0 removals
  - Installing phpbench/phpbench (dev-master 8d1573c): Cloning 8d1573c685 from cache
    8d1573c6859266e932c3586a9d943da54782e0e0 is gone (history was rewritten?)
    Failed to download phpbench/phpbench from source: Failed to execute git checkout "8d1573c6859266e932c3586a9d943da54782e0e0" -- && git reset --hard "8d1573c6859266e932c3586a9d943da54782e0e0" --

Note: checking out '8d1573c6859266e932c3586a9d943da54782e0e0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8d1573c... Fix: Remove unnecessary parentheses (#510)
error: unable to create file docs/assertions-asserters.rst:3:: Invalid argument
fatal: Could not reset index file to revision '8d1573c6859266e932c3586a9d943da54782e0e0'.

    Now trying to download from dist
  - Installing phpbench/phpbench (dev-master 8d1573c): Downloading (100%)

  [RuntimeException]
  The archive may contain identical file names with different capitalization (which fails on case insensitive filesys
  tems): ZipArchive::extractTo(D:\WinTools\Office\Neovim\share\nvim\plugged\phpactor/vendor/composer/bf73a860/phpbenc
  h-phpbench-8d1573c\docs/assertions-asserters.rst:3:): failed to open stream: No such file or directory

  [ErrorException]
  ZipArchive::extractTo(D:\WinTools\Office\Neovim\share\nvim\plugged\phpactor/vendor/composer/bf73a860/phpbench-phpbe
  nch-8d1573c\docs/assertions-asserters.rst:3:): failed to open stream: No such file or directory

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by dantleech** [comment]
Not sure how this happens, however if you change directory to `D:\WinTools\Office\Neovim\share\nvim\plugged\phpactor` and do `git checkout master` and try again it should be fine.

**Comment by geekjam** [comment]
It was fine at linux system, don't know why

**Comment by geekjam** [comment]
[phpbench fix](https://github.com/phpbench/phpbench/issues/513)
